# Generated by Django 3.0.4 on 2021-02-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Pincode',
            field=models.IntegerField(),
        ),
    ]
